Wordfence DB Scan

diff --git a/midgard b/midgard
--- a/midgard
+++ b/midgard
@@ -81,6 +81,7 @@ source "$(dirname "$0")/scripts/scan-maldet"
 # Wordfence scan helpers
 source "$(dirname "$0")/scripts/scan-wordfence-malware"
 source "$(dirname "$0")/scripts/scan-wordfence-vuln"
+source "$(dirname "$0")/scripts/scan-wordfence-db"
 
 # fast-path subcommands that don't need global config
 case "${1-}" in
@@ -189,6 +190,11 @@ for enabled_site in "${ENABLED_SITES[@]}"; do
   # Wordfence Vulnerability
   if ! scan_wordfence_vuln_site "$enabled_site"; then
     echo "    - wordfence vuln scan failed for ${enabled_site}"; exit 1
+  fi
+
+  # Wordfence DB scan
+  if ! scan_wordfence_db_site "$enabled_site"; then
+    echo "    - wordfence db scan failed for ${enabled_site}"; exit 1
   fi
 
 done
