add scan for php in uploads dir

diff --git a/midgard b/midgard
--- a/midgard
+++ b/midgard
@@ -82,6 +82,9 @@ source "$(dirname "$0")/scripts/scan-wordfence-malware"
 source "$(dirname "$0")/scripts/scan-wordfence-vuln"
 source "$(dirname "$0")/scripts/scan-wordfence-db"
 
+# uploads scan for PHP
+source "$(dirname "$0")/scripts/scan-uploads-php"
+
 # Amazon S3 Restic Sync
 source "$(dirname "$0")/scripts/restic-sync"
 
@@ -93,7 +96,6 @@ source "$(dirname "$0")/scripts/report-global"
 
 # Per site mail sending helper
 source "$(dirname "$0")/scripts/sendmail-site"
-
 
 # fast-path subcommands that don't need global config
 case "${1-}" in
@@ -189,6 +191,11 @@ done
 status_start "Websites Inspections"
 echo
 for enabled_site in "${ENABLED_SITES[@]}"; do
+
+  # Uploads PHP Scan
+  if ! scan_uploads_php_site "$enabled_site"; then
+    echo "    - scan for uploads php failed for ${enabled_site}";
+  fi
 
   # ClamAV
   if ! scan_clamav_site "$enabled_site"; then
