Report and Sendmail

diff --git a/midgard b/midgard
--- a/midgard
+++ b/midgard
@@ -15,7 +15,6 @@ cat <<'EOF'
 EOF
 
 EPOCH_TIMESTAMP="$(date +%s)"
-export EPOCH_TIMESTAMP
 
 echo -e " Version : ${MIDGARD_VERSION}\n"
 
@@ -85,6 +84,12 @@ source "$(dirname "$0")/scripts/scan-wordfence-db"
 
 # Amazon S3 Restic Sync
 source "$(dirname "$0")/scripts/restic-sync"
+
+# Report Generation
+source "$(dirname "$0")/scripts/report"
+
+# Per site mail sending helper
+source "$(dirname "$0")/scripts/sendmail-site"
 
 
 # fast-path subcommands that don't need global config
@@ -168,7 +173,7 @@ for enabled_site in "${ENABLED_SITES[@]}"; do
     echo "    - SQL dump failed for ${enabled_site}"
     exit 1
   fi
-
+echo ''
 done
 
 # Start Inpection loop
@@ -204,6 +209,16 @@ for enabled_site in "${ENABLED_SITES[@]}"; do
   # Restic Sync
   if ! restic_sync_site "$enabled_site"; then
     echo "    - restic sync failed for ${enabled_site}"; exit 1
+  fi
+
+  # Generate report Site
+  if ! report_generate_site "$enabled_site"; then
+    echo "    - fail to generate report for ${enabled_site}"; exit 1
+  fi
+
+  # Send report (per-site rules)
+  if ! sendmail_site_report "$enabled_site"; then
+    echo "    - fail to send report email for ${enabled_site}"; exit 1
   fi
 
 done
